# -*- coding: utf-8 -*-
"""Brain_Tumor_MRI_Training.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hOOz1R43BK8YFQQ68NrWR17QljTA8Iyy
"""



"""# Brain Tumor MRI Classification – Training

This notebook trains an image classification model using **EfficientNetB0**.

Outputs:
- Accuracy graph
- Confusion Matrix
- Classification Report
- Saved `.h5` model for Flask deployment
"""

# 4. Unzip it
!unzip d.zip -d dataset

#@title Prepare splits
import random, shutil
from pathlib import Path
import os

random_seed = 42  #@param {type:"integer"}
train_ratio = 0.8  #@param {type:"number"}
val_ratio = 0.1    #@param {type:"number"}
test_ratio = 0.1   #@param {type:"number"}

assert abs(train_ratio + val_ratio + test_ratio - 1.0) < 1e-6, "Ratios must sum to 1."

dataset = 'dataset/dataset' # Define the dataset variable with the correct path
root = Path(dataset)

# Diagnostic: Print current working directory and its contents
print(f"Current working directory: {os.getcwd()}")
print(f"Contents of /content: {os.listdir('/content')}")
if Path('dataset').exists():
    print(f"Contents of /content/dataset: {os.listdir('/content/dataset')}")

assert root.exists(), f"Data path not found: {root}. Please ensure the previous cell (download and unzip) has been run successfully."

# If already split, use it.
if (root / "train").exists() and (root / "val").exists():
    split_root = root
    print("Detected existing split at:", split_root.resolve())
else:
    # Expecting ImageFolder: root//*.jpg
    classes = [d.name for d in root.iterdir() if d.is_dir()]
    assert len(classes) > 0, f"No class subfolders found under {root}"
    split_root = Path("/content/data_split")
    (split_root / "train").mkdir(parents=True, exist_ok=True)
    (split_root / "val").mkdir(parents=True, exist_ok=True)
    (split_root / "test").mkdir(parents=True, exist_ok=True)

    random.seed(random_seed)
    for cls in classes:
        files = [p for p in (root / cls).glob("*") if p.is_file()]
        random.shuffle(files)
        n = len(files)
        n_train = int(n * train_ratio)
        n_val = int(n * val_ratio)
        train_files = files[:n_train]
        val_files = files[n_train:n_train+n_val]
        test_files = files[n_train+n_val:]

        for subset_name, subset_files in [("train", train_files), ("val", val_files), ("test", test_files)]:
            dest_dir = split_root / subset_name / cls
            dest_dir.mkdir(parents=True, exist_ok=True)
            for f in subset_files:
                shutil.copy2(f, dest_dir / f.name)

    print("Created split at:", split_root.resolve())

train_dir = split_root / "train"
val_dir = split_root / "val"
test_dir = split_root / "test" if (split_root / "test").exists() else None
print("train_dir:", train_dir)
print("val_dir:", val_dir)
print("test_dir:", test_dir)

# ===== SETUP =====
import os
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay, classification_report

print("TensorFlow version:", tf.__version__)

"""## Dataset Structure
```
dataset_brain/
 ├── train/
 ├── val/
 └── test/
```
Each class must be inside its own folder.
"""

# ===== CONFIG =====
IMG_SIZE = (224, 224)
BATCH_SIZE = 32
EPOCHS = 8

DATASET_DIR = "/content/dataset_brain"
MODEL_DIR = "/content/models"
os.makedirs(MODEL_DIR, exist_ok=True)

# ===== DATA LOADER =====
def load_datasets(path):
    train_ds = tf.keras.preprocessing.image_dataset_from_directory(
        os.path.join(path, "train"),
        image_size=IMG_SIZE,
        batch_size=BATCH_SIZE
    )
    val_ds = tf.keras.preprocessing.image_dataset_from_directory(
        os.path.join(path, "val"),
        image_size=IMG_SIZE,
        batch_size=BATCH_SIZE
    )
    test_ds = tf.keras.preprocessing.image_dataset_from_directory(
        os.path.join(path, "test"),
        image_size=IMG_SIZE,
        batch_size=BATCH_SIZE
    )
    return train_ds, val_ds, test_ds, train_ds.class_names

# ===== MODEL =====
def build_model(num_classes):
    base = tf.keras.applications.EfficientNetB0(
        include_top=False, weights="imagenet", input_shape=(224,224,3)
    )
    base.trainable = False

    inputs = keras.Input(shape=(224,224,3))
    x = tf.keras.applications.efficientnet.preprocess_input(inputs)
    x = base(x, training=False)
    x = layers.GlobalAveragePooling2D()(x)
    x = layers.Dropout(0.3)(x)
    outputs = layers.Dense(num_classes, activation="softmax")(x)

    model = keras.Model(inputs, outputs)
    model.compile(
        optimizer="adam",
        loss="sparse_categorical_crossentropy",
        metrics=["accuracy"]
    )
    return model

# ===== TRAIN & EVALUATE =====
train_ds, val_ds, test_ds, class_names = load_datasets(DATASET_DIR)
model = build_model(len(class_names))

history = model.fit(train_ds, validation_data=val_ds, epochs=EPOCHS)

model_path = os.path.join(MODEL_DIR, "brain_model.h5")
model.save(model_path)
print("Model saved at:", model_path)

# Accuracy plot
plt.plot(history.history["accuracy"], label="Train Accuracy")
plt.plot(history.history["val_accuracy"], label="Validation Accuracy")
plt.title("Accuracy")
plt.legend()
plt.show()

# Confusion Matrix
y_true, y_pred = [], []
for imgs, labels in test_ds:
    preds = model.predict(imgs)
    y_true.extend(labels.numpy())
    y_pred.extend(np.argmax(preds, axis=1))

cm = confusion_matrix(y_true, y_pred)
disp = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=class_names)
disp.plot(cmap="viridis")
plt.title("Confusion Matrix")
plt.show()

print(classification_report(y_true, y_pred, target_names=class_names))

"""### Next Step
Download the generated `.h5` model and use it in your Flask app.
"""